version: '2'
services:
    okusis-app:
        image: okusis
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://okusis-postgresql:5432/okusis
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    okusis-postgresql:
        extends:
            file: postgresql.yml
            service: okusis-postgresql
